import Link from "next/link";

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-white text-[#111111]">
      <div className="mx-auto max-w-4xl px-6 py-16 sm:px-8 sm:py-24">
        <Link href="/" className="font-bold text-[#C9A227]">
          Back to Home
        </Link>

        <div className="mt-12">
          <p className="text-xs font-black uppercase tracking-[0.2em] text-[#C9A227]">
            Legal
          </p>

          <h1 className="mt-4 text-4xl font-black tracking-tight sm:text-5xl">
            Terms &amp; Conditions
          </h1>

          <p className="mt-5 text-sm text-[#666666]">
            Last updated: October 5, 2026
          </p>
        </div>

        <div className="mt-12 space-y-10 text-[15px] leading-8 text-[#4b4b4b]">
          <section>
            <h2 className="text-2xl font-black text-[#111111]">1. Acceptance of Terms</h2>
            <p className="mt-4">
              By accessing or using MHBlogAI, you agree to these Terms and Conditions.
              If you do not agree with these terms, please do not use the service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-black text-[#111111]">2. About MHBlogAI</h2>
            <p className="mt-4">
              MHBlogAI is an AI-powered writing platform that helps users create,
              improve, and manage written content. Features may change or be updated
              from time to time.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-black text-[#111111]">3. User Accounts</h2>
            <p className="mt-4">
              Some features require an account. You are responsible for providing
              accurate information and keeping your account credentials secure.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-black text-[#111111]">4. AI-Generated Content</h2>
            <p className="mt-4">
              MHBlogAI uses artificial intelligence to generate and assist with
              content. AI-generated content may contain errors or outdated information.
              Users should review and verify content before publishing or relying on it.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-black text-[#111111]">5. User Content</h2>
            <p className="mt-4">
              You are responsible for the text, information, prompts, and other content
              you submit or create through the service. Do not submit content that you
              do not have the right to use or share.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-black text-[#111111]">6. Acceptable Use</h2>
            <p className="mt-4">
              You agree not to use MHBlogAI for unlawful activities, fraud, harmful
              activities, unauthorized access, or attempts to interfere with the
              operation or security of the service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-black text-[#111111]">7. Intellectual Property</h2>
            <p className="mt-4">
              The MHBlogAI website, branding, interface, software, and original service
              materials are protected by applicable intellectual property laws.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-black text-[#111111]">8. Third-Party Services</h2>
            <p className="mt-4">
              MHBlogAI may use third-party services for hosting, authentication,
              database functionality, AI processing, analytics, or other technical
              services. These services may have their own terms and policies.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-black text-[#111111]">9. Service Availability</h2>
            <p className="mt-4">
              We aim to keep MHBlogAI available and reliable, but we do not guarantee
              uninterrupted or error-free operation.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-black text-[#111111]">10. Disclaimer</h2>
            <p className="mt-4">
              MHBlogAI is provided for general writing and content assistance.
              Information generated by the service should not be treated as professional,
              legal, financial, medical, or other specialized advice.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-black text-[#111111]">11. Limitation of Liability</h2>
            <p className="mt-4">
              To the extent permitted by applicable law, MHBlogAI and its operators
              will not be responsible for losses or damages resulting from use of the
              service or reliance on AI-generated content.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-black text-[#111111]">12. Changes to These Terms</h2>
            <p className="mt-4">
              We may update these Terms and Conditions from time to time. Updated terms
              will be posted on this page together with a revised update date.
            </p>
          </section>

          <section className="border-t border-black/10 pt-10">
            <h2 className="text-2xl font-black text-[#111111]">13. Contact</h2>
            <p className="mt-4">
              If you have questions about these Terms and Conditions, please use the
              contact method provided by the website.
            </p>
          </section>
        </div>

        <div className="mt-14 flex flex-wrap gap-6 border-t border-black/10 pt-8 text-sm font-bold">
          <Link href="/" className="hover:text-[#C9A227]">Home</Link>
          <Link href="/about" className="hover:text-[#C9A227]">About</Link>
          <Link href="/privacy" className="hover:text-[#C9A227]">Privacy Policy</Link>
        </div>
      </div>
    </main>
  );
}
